# Natural Language Processing Lab - Assignment 02
## Task 2: WordNet Hypernyms & Ontological Hierarchy Traversal

**Objective**:
1. Select 10 English noun concepts and extract their immediate hypernyms (IS-A relationships).
2. Implement a recursive taxonomic path tracer from a synset up to the root entity (`entity.n.01`).
3. Analyze ontological depth and conceptual hierarchy across sample words.

In [2]:
import nltk
import pandas as pd
from nltk.corpus import wordnet as wn

nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)

# Select 10 diverse noun words
selected_nouns = [
    "dog", "car", "apple", "chair", "oak",
    "doctor", "guitar", "river", "computer", "novel"
]

### 1. Extracting Primary Synsets and Direct Hypernyms

In [3]:
noun_synset_map = {}
direct_hypernym_records = []

for noun in selected_nouns:
    # Select first noun synset
    syn = wn.synsets(noun, pos=wn.NOUN)[0]
    noun_synset_map[noun] = syn
    
    hypernyms = syn.hypernyms()
    hypernym_names = [h.name() for h in hypernyms] if hypernyms else ["None (Root)"]
    
    direct_hypernym_records.append({
        "Noun": noun,
        "Synset": syn.name(),
        "Direct Hypernym(s)": ", ".join(hypernym_names),
        "Definition": syn.definition()
    })

hypernym_table = pd.DataFrame(direct_hypernym_records)
display(hypernym_table)

,Noun,Synset,Direct Hypernym(s),Definition
0,dog,dog.n.01,"canine.n.02, domestic_animal.n.01",a member of the genus Canis (probably descende...
1,car,car.n.01,motor_vehicle.n.01,a motor vehicle with four wheels; usually prop...
2,apple,apple.n.01,"edible_fruit.n.01, pome.n.01",fruit with red or yellow or green skin and swe...
3,chair,chair.n.01,seat.n.03,"a seat for one person, with a support for the ..."
4,oak,oak.n.01,wood.n.01,the hard durable wood of any oak; used especia...
5,doctor,doctor.n.01,medical_practitioner.n.01,a licensed medical practitioner
6,guitar,guitar.n.01,stringed_instrument.n.01,a stringed instrument usually having six strin...
7,river,river.n.01,stream.n.01,a large natural stream of water (larger than a...
8,computer,computer.n.01,machine.n.01,a machine for performing calculations automati...
9,novel,novel.n.01,fiction.n.01,an extended fictional work in prose; usually i...

### 2. Taxonomic Path Traversal to Root Node

In [4]:
def trace_hypernym_lineage(synset):
    """Recursively builds path from the given synset up to entity.n.01"""
    path = [synset.name()]
    current = synset
    while current.hypernyms():
        current = current.hypernyms()[0]
        path.append(current.name())
    return path

# Trace lineage for 5 selected concepts
trace_sample = ["dog", "car", "apple", "doctor", "computer"]

for word in trace_sample:
    syn = noun_synset_map[word]
    lineage = trace_hypernym_lineage(syn)
    print(f"\n{'='*65}\nHIERARCHY CHAIN: {word.upper()} (Depth = {len(lineage)})\n{'='*65}")
    for depth, node in enumerate(reversed(lineage)):
        indent = "  " * depth
        arrow = "└── " if depth > 0 else ""
        print(f"{indent}{arrow}{node}")

=================================================================
HIERARCHY CHAIN: DOG (Depth = 14)
=================================================================
entity.n.01
  └── physical_entity.n.01
    └── object.n.01
      └── whole.n.02
        └── living_thing.n.01
          └── organism.n.01
            └── animal.n.01
              └── chordate.n.01
                └── vertebrate.n.01
                  └── mammal.n.01
                    └── placental.n.01
                      └── carnivore.n.01
                        └── canine.n.02
                          └── dog.n.01

=================================================================
HIERARCHY CHAIN: CAR (Depth = 11)
=================================================================
entity.n.01
  └── physical_entity.n.01
    └── object.n.01
      └── whole.n.02
        └── artifact.n.01
          └── instrumentality.n.03
            └── container.n.01
              └── wheeled_vehicle.n.01
                └── self-propelled_vehicle.n.01
                  └── motor_vehicle.n.01
                    └── car.n.01

=================================================================
HIERARCHY CHAIN: APPLE (Depth = 11)
=================================================================
entity.n.01
  └── physical_entity.n.01
    └── object.n.01
      └── whole.n.02
        └── natural_object.n.01
          └── plant_part.n.01
            └── plant_organ.n.01
              └── reproductive_structure.n.01
                └── fruit.n.01
                  └── edible_fruit.n.01
                    └── apple.n.01

=================================================================
HIERARCHY CHAIN: DOCTOR (Depth = 9)
=================================================================
entity.n.01
  └── physical_entity.n.01
    └── causal_agent.n.01
      └── person.n.01
        └── adult.n.01
          └── professional.n.01
            └── health_professional.n.01
              └── medical_practitioner.n.01
                └── doctor.n.01

=================================================================
HIERARCHY CHAIN: COMPUTER (Depth = 9)
=================================================================
entity.n.01
  └── physical_entity.n.01
    └── object.n.01
      └── whole.n.02
        └── artifact.n.01
          └── instrumentality.n.03
            └── device.n.01
              └── machine.n.01
                └── computer.n.01

### 3. Summary of Ontological Depths

In [5]:
depth_records = []
for word, syn in noun_synset_map.items():
    lineage = trace_hypernym_lineage(syn)
    depth_records.append({
        "Concept": word,
        "Synset": syn.name(),
        "Taxonomic Depth": len(lineage),
        "Root Node": lineage[-1],
        "Full Lineage Path": " -> ".join(reversed(lineage))
    })

depth_df = pd.DataFrame(depth_records).sort_values(by="Taxonomic Depth", ascending=False).reset_index(drop=True)
display(depth_df[["Concept", "Synset", "Taxonomic Depth", "Root Node"]])

    Concept         Synset  Taxonomic Depth    Root Node
0       dog       dog.n.01               14  entity.n.01
1       car       car.n.01               11  entity.n.01
2     apple     apple.n.01               11  entity.n.01
3     chair     chair.n.01               10  entity.n.01
4    guitar    guitar.n.01               10  entity.n.01
5       oak       oak.n.01                9  entity.n.01
6    doctor    doctor.n.01                9  entity.n.01
7  computer  computer.n.01                9  entity.n.01
8     novel     novel.n.01                8  entity.n.01
9     river     river.n.01                6  entity.n.01